/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bacsoftware;

import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yumelir
 */
public class GestionarOpciones extends javax.swing.JFrame {

    /**
     * Creates new form GestionarOpciones
     */
    String act;
    int camb, secc;
    ArrayList<String> categoria, subCategoria;
    
    public GestionarOpciones() {
        initComponents();
        camb =-1;
        cargarInfo();
        
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoLabel = new javax.swing.JLabel();
        nuevoItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        accion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        seccion = new javax.swing.JComboBox<>();
        existeItem = new javax.swing.JComboBox<>();
        existeLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
<<<<<<< HEAD
        labelCateg = new javax.swing.JLabel();
        categ = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
=======
        jButton3 = new javax.swing.JButton();
        labelCateg = new javax.swing.JLabel();
        categ = new javax.swing.JComboBox<>();
>>>>>>> refs/remotes/origin/Luigi

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoLabel.setText("Nuevo Elemento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Software del Banco de Alimentos de Cuernavaca");

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        jLabel1.setText("GESTIÓN DE OPCIONES MÚLTIPLES");

        jLabel6.setText("Acción a realizar:");

        accion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Eliminar", "Modificar" }));

        jLabel7.setText("Sección:");

        seccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoría (Entradas y Salidas)", "Subcategoría (Entradas y Salidas)"}));
        seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccionActionPerformed(evt);
            }
        });

        existeItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        existeLabel.setText("Elemento Existente:");

        jButton1.setText("Guardar Cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelCateg.setText("Categoría:");

        categ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jTextField6.setBackground(new java.awt.Color(0, 102, 0));

        jTextField5.setBackground(new java.awt.Color(255, 102, 0));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacsoftware/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        labelCateg.setText("Categoría:");

        categ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton1)
                        .addGap(233, 233, 233))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(accion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(existeLabel)
                                    .addComponent(nuevoLabel)
                                    .addComponent(labelCateg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(existeItem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nuevoItem, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categ, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
=======
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(existeLabel)
                            .addComponent(nuevoLabel)
                            .addComponent(labelCateg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(existeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categ, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
>>>>>>> refs/remotes/origin/Luigi
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
=======
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1)
>>>>>>> refs/remotes/origin/Luigi
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< HEAD
                .addGap(36, 36, 36)
=======
                .addGap(35, 35, 35)
>>>>>>> refs/remotes/origin/Luigi
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(existeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCateg)
                    .addComponent(categ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< HEAD
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap())
>>>>>>> refs/remotes/origin/Luigi
        );

        setSize(new java.awt.Dimension(705, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql, opc = "";
        int aux, id = 0;
        Conexion con = new Conexion();
        Connection reg = con.conexion();
        boolean repeat = true;
        PreparedStatement pst;
        
        if(secc == 0)
        {
            sql = "SELECT COUNT(nombreCategoria) FROM categoria WHERE nombreCategoria = '" + nuevoItem.getText() + "'";
            try {
                Statement st;
                st = reg.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next())
                {
                    if(rs.getString(1).equals("1")) 
                    {
                        JOptionPane.showMessageDialog(null, "ERROR: Categoría ya existente");
                        nuevoItem.setText("");
                        
                    }else repeat = false;
                    
                    //System.out.println(id);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GestionarOpciones.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }else
        {
            sql = "SELECT COUNT(nombreSubcategoria) FROM subcategoria WHERE nombreSubcategoria = '" + nuevoItem.getText() + "'";
            try {
                Statement st;
                st = reg.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next())
                {
                    if(rs.getString(1).equals("1")) 
                    {
                        JOptionPane.showMessageDialog(null, "ERROR: Categoría ya existente");
                        nuevoItem.setText("");
                        
                    }else repeat = false;
                    
                    //id = rs.getInt(2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(GestionarOpciones.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
        
        
        
        switch(act)
        {
            case "Agregar":
                if(!repeat)
                {
                    try
                    {
                        if(secc == 0)
                        {
                            sql = "INSERT INTO categoria(nombreCategoria) VALUES (?)";
                            pst = reg.prepareStatement(sql);
                            pst.setString(1, nuevoItem.getText());
                            
                        }else
                        {
                            int idCat = 0;
                            sql = "SELECT idCategoria FROM categoria WHERE nombreCategoria = '" + categ.getSelectedItem().toString() + "'";
                            Statement st;
                            st = reg.createStatement();
                            ResultSet rs = st.executeQuery(sql);
                            while(rs.next())
                            {
                                idCat = rs.getInt(1);
                            }
                            
                            sql = "INSERT INTO subcategoria(nombreSubcategoria, fk_idCategoria) VALUES (?,?)";
                            pst = reg.prepareStatement(sql);
                            pst.setString(1, nuevoItem.getText());
                            pst.setInt(2, idCat);
                        }
                        
                        aux = pst.executeUpdate();
                        if(aux > 0)
                        {
                            JOptionPane.showMessageDialog(null, "Registrado con éxito");
                            nuevoItem.setText("");
                        }
                        
                    } catch(Exception ex)
                    {
                        Logger.getLogger(GestionarOpciones.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                break;
                
            case "Eliminar":
<<<<<<< HEAD
                /*nuevoLabel.setVisible(false);
                nuevoItem.setVisible(false);
                existeLabel.setVisible(true);
                existeItem.setVisible(true);  */              
=======
                try
                {
                    if(secc == 0)
                    {
                        sql = "DELETE FROM categoria WHERE nombreCategoria = ?";
                        pst = reg.prepareStatement(sql);
                        pst.setString(1, existeItem.getSelectedItem().toString());
                        aux = pst.executeUpdate();
                    }else
                    {
                        sql = "DELETE FROM subcategoria WHERE nombreSubcategoria = ?";
                        pst = reg.prepareStatement(sql);
                        pst.setString(1, existeItem.getSelectedItem().toString());
                        aux = pst.executeUpdate();
                    }
                    
                    if(aux > 0)
                        JOptionPane.showMessageDialog(null, "Eliminado con éxito");
                } catch (SQLException ex) {
                    Logger.getLogger(GestionarOpciones.class.getName()).log(Level.SEVERE, null, ex);
                }
                             
>>>>>>> refs/remotes/origin/Luigi
                break;
                
            case "Modificar":
                if(!repeat)
                {
                    try
                    {
                        if(secc == 0)
                        {
                            sql = "SELECT idCategoria FROM categoria WHERE nombreCategoria = '" + existeItem.getSelectedItem().toString() + "'";
                            Statement st;
                            st = reg.createStatement();
                            ResultSet rs = st.executeQuery(sql);
                            while(rs.next())
                            {
                                id = rs.getInt(1);
                            }
                            
                            sql = "UPDATE categoria SET nombreCategoria = ? WHERE idCategoria = ?";
                        }                    
                        else
                        {
                            sql = "SELECT idSubcategoria FROM subcategoria WHERE nombreSubcategoria = '" + existeItem.getSelectedItem().toString() + "'";
                            Statement st;
                            st = reg.createStatement();
                            ResultSet rs = st.executeQuery(sql);
                            while(rs.next())
                            {
                                id = rs.getInt(1);
                            }
                            sql = "UPDATE subcategoria SET nombreSubcategoria = ? WHERE idSubcategoria = ?";
                        }
                        
                            pst = reg.prepareStatement(sql);
                            opc = nuevoItem.getText();
                            pst.setString(1, opc);
                            pst.setInt(2, id);
                            
                            aux = pst.executeUpdate();
                            
                            if(aux > 0)
                            {
                                JOptionPane.showMessageDialog(null, "Modificación exitosa");
                                nuevoItem.setText("");
                            }
                            
                            //System.out.println(id);
                            
                    } catch (Exception ex)
                    {
                        Logger.getLogger(GestionarOpciones.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                break;
        }
        
        cargarInfo();
        //showOpc();
        camb = -1;
        //existeItem.setSelectedItem(opc);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        Inicio newFrame = new Inicio();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void cargarInfo()
    {
        categoria = new ArrayList<>();
        subCategoria = new ArrayList<>();
        String sql;
        Conexion con = new Conexion();
        Connection reg = con.conexion();
        
        sql = "SELECT nombreCategoria FROM categoria";
        
        try {
            Statement st;
            st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                categoria.add(rs.getString(1));
            }
            
            sql = "SELECT nombreSubcategoria FROM subcategoria";
            
            st = reg.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                subCategoria.add(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GestionarOpciones.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
    }
    
    public void showOpc()
    {
        String sql;
        act = accion.getSelectedItem().toString();
        secc = seccion.getSelectedIndex();
        
        
        //existeItem.removeAllItems();
        if(camb != secc)
        {
             existeItem.removeAllItems();
             //REMOVER TODO DE LA LISTA;
            if(secc == 0)
            {
                for(int n = 0; n < categoria.size(); n++)
                {
                    existeItem.addItem(categoria.get(n).toString());
                }
                
                camb = 0;
            
            }else
            {
                for(int n = 0; n < categoria.size(); n++)
                {
                    categ.addItem(categoria.get(n).toString());
                }
                
                for(int n = 0; n < subCategoria.size(); n++)
                {
                    existeItem.addItem(subCategoria.get(n).toString());
                }
                camb = 1;
            }
            
        }
        
        
        
        
        switch(act)
        {
            case "Agregar":
                existeLabel.setVisible(false);
                existeItem.setVisible(false);
                nuevoLabel.setVisible(true);
                nuevoItem.setVisible(true);
                if(secc == 1)
                {
                    labelCateg.setVisible(true);
                    categ.setVisible(true);
                }else
                {
                    labelCateg.setVisible(false);
                    categ.setVisible(false);
                }
                    
                break;
                
            case "Eliminar":
                nuevoLabel.setVisible(false);
                nuevoItem.setVisible(false);
                existeLabel.setVisible(true);
                existeItem.setVisible(true);  
                labelCateg.setVisible(false);
                categ.setVisible(false);
                break;
                
            case "Modificar":
                nuevoLabel.setVisible(true);
                nuevoItem.setVisible(true);
                existeLabel.setVisible(true);
                existeItem.setVisible(true);
                labelCateg.setVisible(false);
                categ.setVisible(false);
                break;
        }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        GestionarOpciones opc = new GestionarOpciones();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                opc.setVisible(true);
            }
        });
        
        while(true)
        {
            opc.showOpc();
        }
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accion;
    private javax.swing.JComboBox<String> categ;
    private javax.swing.JComboBox<String> existeItem;
    private javax.swing.JLabel existeLabel;
    private javax.swing.JButton jButton1;
<<<<<<< HEAD
    private javax.swing.JButton jButton2;
=======
    private javax.swing.JButton jButton3;
>>>>>>> refs/remotes/origin/Luigi
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
<<<<<<< HEAD
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
=======
>>>>>>> refs/remotes/origin/Luigi
    private javax.swing.JLabel labelCateg;
    private javax.swing.JTextField nuevoItem;
    private javax.swing.JLabel nuevoLabel;
    private javax.swing.JComboBox<String> seccion;
    // End of variables declaration//GEN-END:variables
}
